version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongo_db_tracker_boost
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_tracker_boost
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

  app:
    build: .
    container_name: project_tracker_boost
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - grafana
      - prometheus
      - redis
    environment:
      spring.datasource.url: ${DOCKER_DB_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.data.mongodb.uri: ${DOCKER_MONGODB_URI}
      spring.security.oauth2.client.registration.google.client-id: ${GOOGLE_AUTH_CLIENT_ID}
      spring.security.oauth2.client.registration.google.client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:
  grafana_data:
  prometheus_data:

networks:
  backend:
